const types = {
    CLEAR_CURRENT: 'RESTAURANTES_CLEAR_CURRENT',
    GET_REQUEST: 'RESTAURANTES_GET_REQUEST',
    GET_SUCCESS: 'RESTAURANTES_GET_SUCCESS',
    GET_FAILURE: 'RESTAURANTES_GET_FAILURE',
  
    POST_REQUEST: 'RESTAURANTES_POST_REQUEST',
    POST_SUCCESS: 'RESTAURANTES_POST_SUCCESS',
    POST_FAILURE: 'RESTAURANTES_POST_FAILURE',
  
    GETALL_REQUEST: 'RESTAURANTES_GETALL_REQUEST',
    GETALL_SUCCESS: 'RESTAURANTES_GETALL_SUCCESS',
    GETALL_FAILURE: 'RESTAURANTES_GETALL_FAILURE',
    CLEAR_ALL: "RESTAURANTES_CLEAR_ALL",

    GET_MY_RESTAURANTS_REQUEST: 'RESTAURANTES_GET_MY_RESTAURANTS_REQUEST',
    GET_MY_RESTAURANTS_SUCCES: 'RESTAURANTES_GET_MY_RESTAURANTS_SUCCES',
    GET_MY_RESTAURANTS_FAILURE: 'RESTAURANTES_GET_MY_RESTAURANTS_FAILURE',
  
    DELETE_REQUEST: 'RESTAURANTES_DELETE_REQUEST',
    DELETE_SUCCESS: 'RESTAURANTES_DELETE_SUCCESS',
    DELETE_FAILURE: 'RESTAURANTES_DELETE_FAILURE',    
  
    UPDATE_REQUEST: 'RESTAURANTES_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'RESTAURANTES_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'RESTAURANTES_UPDATE_FAILURE'    
  
  };
  
  export default types;